name: ci
on: push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.2
      - name: Install dependencies
        run: go mod tidy
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          skip-go-installation: true
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.2
      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: go build .
  test:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.2
      - name: Install dependencies
        run: go mod tidy
      - name: Test
        run: go test ./... -v -coverprofile=coverage.txt -covermode=atomic
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
